kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.15192283047976676
    roll: -0
    pitch: 0
    yaw: -5.7268099108373494e-08
  upper_arm:
    x: -0.00019515468864545848
    y: 0
    z: 0
    roll: 1.5704735255000193
    pitch: 0
    yaw: -1.8483950676717602e-06
  forearm:
    x: -0.24394101790978492
    y: 0
    z: 0
    roll: 3.1401781021222659
    pitch: 3.1400932105845056
    yaw: 3.1415829414736862
  wrist_1:
    x: -0.21325457546021262
    y: -0.00052294109679795742
    z: 0.13132703065685788
    roll: 0.0039819550496753833
    pitch: 0.00099971550725664595
    yaw: 4.1497974616442156e-06
  wrist_2:
    x: 3.8098937326559678e-05
    y: -0.085240873111775473
    z: 5.5115765463562243e-05
    roll: 1.5701497384180927
    pitch: 0
    yaw: -1.1522983195307317e-06
  wrist_3:
    x: -8.1270623715697077e-05
    y: 0.092269931080055295
    z: -0.00020404567922847089
    roll: 1.5685849309021394
    pitch: 3.1415926535897931
    yaw: -3.1415925482156024
  hash: calib_15106471971166357553